name: inventory_management
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Circular
      fonts:
        - asset: assets/fonts/Circular/Bold.ttf
          weight: 600
        - asset: assets/fonts/Circular/Book.ttf
          weight: 500
        - asset: assets/fonts/Circular/Medium.ttf
          weight: 400
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir/Medium.ttf
          weight: 500
        - asset: assets/fonts/Avenir/Heavy.ttf
          weight: 600
                    