name: inventory_management
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  bloc: ^8.0.2
  charts_flutter: ^0.12.0
  date_time_picker: ^2.1.0
  fl_chart: ^0.46.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  font_awesome_flutter: ^10.1.0
  freezed: ^1.1.1
  freezed_annotation: ^1.1.0
  hive: ^2.0.5
  http: ^0.13.4
  intl: ^0.17.0
  path_provider: ^2.0.8
  provider: ^6.0.2
  syncfusion_flutter_datagrid: ^20.1.47
  uuid: ^3.0.5

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.2
  json_serializable: ^6.1.4

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir/Medium.ttf
          weight: 500
        - asset: assets/fonts/Avenir/Heavy.ttf
          weight: 600

    - family: AndroidEuclid
      fonts:
        - asset: assets/fonts/AndroidEuclid/Medium.otf

    - family: circular
      fonts:
        - asset: assets/fonts/Circular.otf
          weight: 400
        - asset: assets/fonts/Circular-Medium.otf
          weight: 500
        - asset: assets/fonts/Circular-Bold.otf
          weight: 600