name: inventory_management
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed: ^1.1.1
  bloc: ^8.0.2
  provider: ^6.0.2
  hive: ^2.0.5
  freezed_annotation: ^1.1.0
  flutter_bloc: ^8.0.1
  path_provider: ^2.0.8
  uuid: ^3.0.5
  date_time_picker: ^2.1.0
  http: ^0.13.4
  syncfusion_flutter_charts: ^19.4.56
  syncfusion_flutter_datagrid: ^19.4.56
  charts_flutter: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  hive_generator: ^1.1.2
  build_runner: ^2.1.7
  json_serializable: ^6.1.4

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir/Medium.ttf
          weight: 500
        - asset: assets/fonts/Avenir/Heavy.ttf
          weight: 600
    - family: AndroidEuclid
      fonts:
        - asset: assets/fonts/AndroidEuclid/Medium.otf                    